config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'
  get 'about', to:'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>
  <link 
    rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
  />
  <link rel="stylesheet" href="assets/css/style.css"/>
    <title>Aaron Saralegui - Web Developer</title>
</head>
<body>
  
      <main>
        <div class="menu">
          <div class="menu-icon" id="sidebarCollapse"><i class="fas fa-bars"></i> <span class="mobile-header">Your Name: Web Developer</span></div>
        </div>
        <h1>About</h1>
        <article>
          <img class="about-image" src="http://via.placeholder.com/200" />
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dapibus mauris eu
            nunc dictum, sit amet elementum turpis viverra. Morbi vel tristique sem. Vivamus vel finibus velit,
            sit amet dictum enim. Sed ac risus mi. Maecenas non lectus vitae magna laoreet pretium. Aenean leo
            turpis, facilisis sed suscipit non, viverra non ex. Duis elementum lorem nulla, nec sollicitudin eros feugiat in.
            In dignissim maximus nibh, eu faucibus nisl suscipit eget.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dapibus mauris eu
            nunc dictum, sit amet elementum turpis viverra. Morbi vel tristique sem. Vivamus vel finibus velit,
            sit amet dictum enim. Sed ac risus mi. Maecenas non lectus vitae magna laoreet pretium. Aenean leo
            turpis, facilisis sed suscipit non, viverra non ex. Duis elementum lorem nulla, nec sollicitudin eros feugiat in.
            In dignissim maximus nibh, eu faucibus nisl suscipit eget.
          </p>
        </article>
        <footer>
          Made with ❤️ in Your Location Here. © 2018 All Rights Reserved
        </footer>
      </main>

app/views/blog/contact.html.erb
!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>
  <link 
    rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
  />
  <link rel="stylesheet" href="assets/css/style.css"/>
    <title>Aaron Saralegui - Web Developer</title>
</head>
<body>

      <main>
        <div class="menu">
          <div class="menu-icon" id="sidebarCollapse"><i class="fas fa-bars"></i> <span class="mobile-header">Your Name: Web Developer</span></div>
        </div>
        <h1>Contact</h1>
        <h2>Want to work together? Hit me up online!</h2>
        <hr />
        <ul class="social">
          <li><i class="fab fa-github"></i> <a href="#">Github</a></li>
          <li><i class="fab fa-linkedin"></i> <a href="#">LinkedIn</a></li>
          <li><i class="fab fa-twitter"></i> <a href="#">Twitter</a></li>
        </ul>
        <h2>Or drop me an <a href="#"><i class="fas fa-envelope"></i> Aaron.saralegui@gmail.com</a>.</h2>
        <footer>
          Made with ❤️ in Your Location Here. © 2018 All Rights Reserved
        </footer>
      </main>

    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="assets/js/sidebar.js"></script>
</body>
</html>

app/views/blog/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>
  <link 
    rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
  />
  <link rel="stylesheet" href="assets/css/style.css"/>
    <title>Aaron Saralegui - Web Developer</title>
</head>
<body>
  
      <main>
        <div class="menu">
          <div class="menu-icon" id="sidebarCollapse">
            <i class="fas fa-bars"></i>
            <span class="mobile-header">Aaron Saralegui: Web Developer</span>
          </div>
        </div>
        <h1>My blog</h1>
        <article>
          <h2>My experience with git</h2>
          <hr />
          <h3>Sarturday August 3, 2019</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dapibus mauris eu nunc
            dictum, sit amet elementum turpis viverra. Morbi vel tristique sem. Vivamus vel finibus velit, sit amet
            dictum enim. Sed ac risus mi. Maecenas non lectus vitae magna laoreet pretium. Aenean leo turpis, facilisis
            sed suscipit non, viverra non ex. Duis elementum lorem nulla, nec sollicitudin eros feugiat in. In
            dignissim maximus nibh, eu faucibus nisl suscipit eget.
          </p>
          <p>
           Cras ac odio viverra, semper est id, facilisis lectus. Aliquam eget sollicitudin eros, at posuere lorem.
            Sed consectetur libero elit, sit amet ultrices eros auctor mollis. Praesent egestas blandit rutrum. Phasellus vel pretium nulla. Donec ut varius sapien. In maximus tincidunt lorem egestas eleifend. Vestibulum cursus ante
            eget urna tempor, quis viverra mauris viverra. Ut nibh lorem, bibendum in accumsan quis, ullamcorper sed
            tortor. Integer blandit aliquam nibh in pulvinar. Curabitur a malesuada purus, at scelerisque ligula. Morbi
            malesuada pellentesque neque, id condimentum purus finibus eu.
          </p>
        </article>
        <article>
          <h2>Welcome</h2>
          <hr />
          <h3>Thursday August 1, 2019</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipiscing elit. Morbi dapibus mauris eu nunc
            dictum, sit amet elementum turpis viverra. Morbi vel tristique sem. Vivamus vel finibus velit, sit amet
            dictum enim. Sed ac risus mi. Maecenas non lectus vitae magna laoreet pretium. Aenean leo turpis, facilisis
            sed suscipit non, viverra non ex. Duis elementum lorem nulla, nec sollicitudin eros feugiat in. In
            dignissim
            maximus nibh, eu faucibus nisl suscipit eget.
          </p>
          <p>
            Cras ac odio viverra, semper est id, facilisis lectus. Aliquam eget sollicitudin eros, at posuere lorem.
            Sed
            consectetur libero elit, sit amet ultrices eros auctor mollis. Praesent egestas blandit rutrum. Phasellus
            vel
            pretium nulla. Donec ut varius sapien. In maximus tincidunt lorem egestas eleifend. Vestibulum cursus ante
            eget urna tempor, quis viverra mauris viverra. Ut nibh lorem, bibendum in accumsan quis, ullamcorper sed
            tortor. Integer blandit aliquam nibh in pulvinar. Curabitur a malesuada purus, at scelerisque ligula. Morbi
            malesuada pellentesque neque, id condimentum purus finibus eu.
          </p>
        </article>
        <footer>
          Made with ❤️ Arizona. © 2019 All Rights Reserved
        </footer>

      </main>

    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="assets/js/sidebar.js"></script>
</body>
</html>

app/views/blog/portfolio.html.erb
!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>
  <link 
    rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
  />
  <link rel="stylesheet" href="assets/css/style.css"/>
    <title>Aaron Saralegui - Web Developer</title>
</head>
<body>

        <main>
          <div class="menu">
            <div class="menu-icon" id="sidebarCollapse"><i class="fas fa-bars"></i> <span class="mobile-header">Your Name: Web Developer</span></div>
          </div>
          <h1>Portfolio</h1>

          <article class="portfolio-item">
            <div class="portfolio-image">
              <img src="http://via.placeholder.com/150" />
            </div>
            <div class="portfolio-description">
              <h2>Cool project</h2>
              <h3>This is a mighty cool project I did in class.
                <a href="#"><i class="fas fa-arrow-alt-circle-right"></i></a>
              </h3>
              <hr />
            </div>
          </article>

          <article class="portfolio-item">
            <div class="portfolio-image">
              <img src="http://via.placeholder.com/150" />
            </div>
            <div class="portfolio-description">
              <h2>Cool project</h2>
              <h3>This is a mighty cool project I did in class. 
                <a href="#"><i class="fas fa-arrow-alt-circle-right"></i></a>
              </h3>
              <hr />
              </div>
          </article>

          <article class="portfolio-item">
            <div class="portfolio-image">
              <img src="http://via.placeholder.com/150" />
            </div>
            <div class="portfolio-description">
              <h2>Cool project</h2>
              <h3>This is a mighty cool project I did in class. 
                <a href="#"><i class="fas fa-arrow-alt-circle-right"></i></a>
              </h3>
              <hr />
            </div>
          </article>

          <footer>
            Made with ❤️ in Your Location Here. © 2018 All Rights Reserved
          </footer>
        </main>

    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="assets/js/sidebar.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitBlog1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="parent">
    <div class="wrapper">
      <nav>
        <div class="inner-wrap">
          <div class="site-header">Aaron Saralegui</div>
          <div class="site-subheader">Web Developer</div>
          <ul class="site-navigation">
            <li><a href="index.html"><i class="fas fa-home"></i> Home</a></li>
            <%=link_to 'about', about_path %>
            <li><a href="/about"><i class="fas fa-id-card"></i> About</a></li>
            <li><a href="contact.html"><i class="fas fa-comment-dots"></i> Contact</a></li>
            <li><a href="portfolio.html"><i class="fas fa-gem"></i> Portfolio</a></li>
          </ul>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>